# ~/.zshrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ssh="kitten ssh"
alias ff="fastfetch"
alias neofetch="fastfetch"
alias v="nvim"
alias d="kitty . > /dev/null 2>&1 & disown"
alias c="clear"
alias f="fuck"
alias p="python"
alias lg="lazygit"
alias calc="qalculate-gtk > /dev/null 2>&1 & disown"
alias pip="python -m pip"
alias copilot="gh copilot"
alias zconf="nvim ~/.config/dotfiles/zsh/zshrc"
alias vconf="nvim ~/.config/dotfiles/nvim/init.vim"
alias reload="source ~/.zshrc"
alias pipuall="pip uninstall -y -r <(pip freeze)"

autoload -U promptinit
promptinit

PROMPT='[%n@%m %~]%# '

eval "$(thefuck --alias)"
eval "$(starship init zsh)"

if [[ $(uname) == "Darwin" ]]; then 
    # MacOS Only
    source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
else
    # Linux Only
    alias hconf="nvim ~/.config/dotfiles/hypr/hyprland.conf" 
    alias wl="~/.config/dotfiles/launcher.sh"
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
fi
